version: '3.8'

services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    environment:
      - SERVICES=sqs
      - GATEWAY_LISTEN=4566
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=fakeAccessKey
      - AWS_SECRET_ACCESS_KEY=fakeSecretKey
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    volumes:
      - "./localstack:/var/lib/localstack"
    networks:
      - san-giorgio-network

  db:
    image: postgres:16
    container_name: postgres_container
    environment:
      POSTGRES_DB: san-giorgio-challenge
      POSTGRES_USER: san-giorgio
      POSTGRES_PASSWORD: san-giorgio
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - san-giorgio-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: san-giorgio-api
    environment:
      POSTGRES_URL: jdbc:postgresql://db:5432/san-giorgio-challenge
      POSTGRES_USER: san-giorgio
      POSTGRES_PASSWORD: san-giorgio
      AWS_ENDPOINT: http://localstack:4566
      AWS_DEFAULT_REGION: us-east-1
      AWS_ACCESS_KEY_ID: fakeAccessKey
      AWS_SECRET_ACCESS_KEY: fakeSecretKey
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8080:8080"
    depends_on:
      - db
      - localstack
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    networks:
      - san-giorgio-network

networks:
  san-giorgio-network:

volumes:
  postgres_data:
