version: '3.8'

services:
  elasticmq:
    image: softwaremill/elasticmq-native
    container_name: elasticmq
    ports:
      - "9324:9324"
      - "9325:9325"
    network_mode: host

  db:
    image: postgres:16
    container_name: postgres_container
    environment:
      POSTGRES_DB: san-giorgio-challenge
      POSTGRES_USER: san-giorgio
      POSTGRES_PASSWORD: san-giorgio
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    network_mode: host

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: san-giorgio-api
    environment:
      POSTGRES_URL: jdbc:postgresql://localhost:5432/san-giorgio-challenge
      POSTGRES_USER: san-giorgio
      POSTGRES_PASSWORD: san-giorgio
      AWS_ENDPOINT: http://localhost:9324
      AWS_DEFAULT_REGION: us-east-1
      AWS_ACCESS_KEY_ID: fakeAccessKey
      AWS_SECRET_ACCESS_KEY: fakeSecretKey
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8080:8080"
    depends_on:
      - db
      - elasticmq
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    network_mode: host

volumes:
  postgres_data:
