spring:
  application:
    name: san-giorgio-challenge
  config:
    activate:
      on-profile: prod
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
cloud:
  aws:
    sqs:
      endpoint: ${AWS_ENDPOINT}
      region: ${AWS_DEFAULT_REGION}
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_ACCESS_KEY}